- name: Add required packages
  package:
    name:
      - apt-transport-https
      - ca-certificates 
      - curl
      - software-properties-common
      - gnupg2

- name: "Create containerd modules file"
  template:
    src: containerd.conf.j2
    dest: /etc/modules-load.d/containerd.conf

- name: Ensure the overlay module is loaded
  community.general.modprobe:
    name: overlay
    state: present

- name: Ensure the br_netfilter module is loaded
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: Apply sysctl params without reboot
  shell: sysctl --system

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker CE Repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: true

- name: "Install containerd packages"
  package:
    name:
      - containerd.io

- name: Finalise containerd setup
  shell: |
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml
    systemctl restart containerd