- hosts: 127.0.0.1
  connection: local
  tasks:
    - import_role:
        name: helm-longhorn
      vars:
        namespace: longhorn-system
        username: "{{ global_ingress.basic_auth_username }}"
        password: "{{ global_ingress.basic_auth_password }}"
        domain: "longhorn.{{ global_ingress.base_domain }}"
        tls: "{{ global_ingress.tls }}"
        longhorn_certificate_issuer: "{{ global_ingress.certificate_issuer }}"
        longhorn_ui_force_tls: "{{ global_ingress.force_tls }}"