---
- name: Create the master nodes
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - import_role:
        name: hetzner_cloud_cluster
      vars:
        hetzner_cloud_cluster:
          state: present

    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]