- name: 'Create the namespace'
  shell: |
    export KUBECONFIG={{ global_master_kubeconf }}
    echo "{{ lookup('template', 'namespace.yml.j2') }}" | kubectl apply -f - \

- name: 'Create the basic auth secret'
  shell: |
    export KUBECONFIG={{ global_master_kubeconf }}
    echo "{{ lookup('template', 'basic-auth-creds.yml.j2') }}" | kubectl apply -f - \

- name: 'Create the AWS credentials secret'
  shell: |
    export KUBECONFIG={{ global_master_kubeconf }}
    echo "{{ lookup('template', 'aws-s3-creds.yml.j2') }}" | kubectl apply -f - \
  when: global_longhorn.backups.enabled == true

- name: 'Create a tempfile for the values config'
  tempfile:
    state:  file
  register: values

- name: Create the values file
  template:
    src: values.yml.j2
    dest: "{{values.path}}"
    force: yes

- name: 'Make sure we have the Longhorn helm repos'
  shell: |
    helm repo add longhorn https://charts.longhorn.io
    helm repo update

- name: 'Install Longhorn with Helm'
  shell: |
    KUBECONFIG={{ global_master_kubeconf }} helm upgrade --install longhorn longhorn/longhorn \
    -f {{ values.path }} \
    --namespace {{ namespace }}